serverAddr = "gaianet.network"
serverPort = 7000
metadatas.deviceId = ""

[[proxies]]
name = "{your_subdomain}.gaianet.network"
type = "http"
localPort = 8080
#remotePort = 80
subdomain = "{your_subdomain}"
