
[api]
enabled = false

[sources.api_server_logs]
type = "stdin"

# [sinks.console]
# inputs = ["api_server_logs"]
# target = "stdout"
# type = "console"
# encoding.codec = "json"

[sinks.log_file]
type = "file"
inputs = ["api_server_logs"]
path = "log/gaianet-api-server.log"
encoding.codec = "json"

# [sinks.aws_s3]
# type = "aws_s3"
# inputs = [ "api_server_logs" ]
# bucket = "my-bucket"
